### PR TITLE
Extra textures from the DX version

### PR DESCRIPTION
**Pull request by slashdevslashurandom**
This is a pull request containing all the changes I made in the "Pixel Perfection DX" mod, namely:

* new textures for powered and brake rails
* fixed textures for fence rails, glass pane sides/tops/bottoms and iron bar tops/bottoms
* blueberry, blueberry bush and coral textures

All of these are either made by me or modifications of textures in the original MineCraft PP texture pack. I have removed all the branding-related changes from the pull request, so the texture pack name and screenshots shall not be changed upon merging.

### CODE REVIEW

**Comment by tacotexmex** [comment]
screenshot_20230625_112555

Thanks! Just checking, should blueberry bushes be this bright?

**Comment by slashdevslashurandom** [comment]
I looked at the original PixelPerfection texture set for MineCraft, and the ones that matched the closest were the sweetberry bushes, so I used those as the base.

**Comment by tacotexmex** [comment]
bild
The colors does look a little washed out compared to the sweetberry bush palette so I suspect color profile issues. Could that be the case?


Not that it looks bad per se! ❤️

**Comment by slashdevslashurandom** [comment]
IIRC I picked the colors from [this texture](https://github.com/Athemis/PixelPerfectionCE/blob/master/assets/minecraft/textures/block/sweet_berry_bush_stage3.png), which does look a bit different (different version of the pack?)

**Comment by tacotexmex** [comment]
Ah yes, there's our problem. Major color disparity. That repo is old and stale so I suggest going forward everyone should use [minetest-texture-packs/Pixel-Perfection-Legacy](https://github.com/minetest-texture-packs/Pixel-Perfection-Legacy/) as source. 

The sweetberry bush of that texture source looks sane: , as opposed to .

**Comment by slashdevslashurandom** [comment]
Thanks for the information, I changed the bush leaves' colors to be based on the Pixel Perfection Legacy's sprite instead.

**Comment by tacotexmex** [comment]
Before a1438ff
screenshot_20230626_112056

After a1438ff
screenshot_20230626_112145

Looks like something went wrong when compared to the sweetberry bush textures placed in-game for comparison. The previous version looks closer to source than a1438ff.

Sorry for being picky but we might as well get the process right from the start so that you don't go ahead and do 100s of textures based on a faulty palette. 🙂

**Comment by slashdevslashurandom** [comment]
I just checked both files, and they seem to use the standard sRGB color profile. I think this might be an issue with the lighting in this specific screenshow, rather than the actual palette.

Here I made my own screenshot of the modified files (I temporarily replaced the jungle sapling's texture with the sweetberry's), and the colors seem to match.

bildo

**Comment by tacotexmex** [comment]
lgtm! PP users will enjoy this expanded texture coverage 🙌

**Comment by slashdevslashurandom** [comment]
Honestly I just made my mod for myself, and it's nice that it's now part of the official set. I was annoyed that some vanilla textures clashed with modded ones too much. I might make and pull-request some more additions/changes later, but it's unlikely.

**Pull request merged**
